##############################>
home:
  hosts:
    localhost:
      ansible_host: 127.0.0.1
  vars:
    ansible_user: my_user
ec2hosts:
  vars:
    ansible_ssh_private_key_file: /path-to/mccert.pem
  hosts:
mysql:
  vars:
    ansible_ssh_private_key_file: /path-to/mccert.pem
  hosts:
apache:
  vars:
    ansible_ssh_private_key_file: /path-to/mccert.pem
  hosts:

